### ISSUE TITLE
Table structure distrubed

### ISSUE THREAD

**Issue by usman-whizpool** [editfmah/sharkorm#112]
after updating xcode and your sdk via pod file update..
facing some wired issues..

profile table is auto restructured to some other values,,,

see both screenshots... the change occurred after initialzing table object to store values
table name: Profile

change occurred after this line
var profileObj = Profile()
<img width="650" alt="after auto change" src="https://user-images.githubusercontent.com/5094671/45691006-11da0700-bb71-11e8-91a8-12addb06ee64.png">
<img width="915" alt="before any change" src="https://user-images.githubusercontent.com/5094671/45691007-11da0700-bb71-11e8-8b9b-ea62c9106a4d.png">

any help... our product is live and need to send update asap.

**Comment by editfmah** [comment]
Okay i'll look into it right now.  But i'll need to know, is this an iOS12 SDK compile?  Are the definitions in Swift or Obj-c.

When was it last okay?

Because the second table does not look like a SharkORM table, it has no `Id` column, and your primary key is a non-standard TEXT PRIMARY KEY (e.g. not defined as an SRK_TEXT_PRIMARY_KEY_COLUMN) object.

**Comment by editfmah** [comment]
This is an example application which create the table (correctly form the class model).  Can you check you are using the ORM in the same way please?

[srktest.zip](https://github.com/sharksync/sharkorm/files/2393002/srktest.zip)

**Comment by usman-whizpool** [comment]
yes its ios 12 compile. it was all okay before upgrading your sdk... 
i installed latest xcode... and then updated all pods

**Comment by usman-whizpool** [comment]
yes its ios 12 compile. definition is for swift...
it was all okay before upgrading your sdk... 
i installed latest xcode... and then updated all pods

**Comment by usman-whizpool** [comment]
thanks for sharing sample.. we are following same...

**Comment by usman-whizpool** [comment]
reverted back to SharkORM 2.1.3 (was 2.3.62)..
working fine... need to send update of our app... will catch you later with it after update

**Comment by usman-whizpool** [comment]
hello any update about it...

**Comment by editfmah** [comment]
We would probably require a sample application demonstrating the fault, as we have had no other reports of the issue from other sources. 

There is much to be explained or understood, because your profile table does not adhere to any of the normal SharkORM rules, not having the standard PK column etc....

We would definitely need more information, or for you to debug the `setupClass` method to work out if your classes are being inspected correctly or not.  What list of fields are being generated, etc..

There is just nothing like enough information to go on in this report for anyone to even start knowing where to look at this issue.

Although I agree that the creation of NUMBER, TEXT, INTEGER as columns suggests a bug in the creation of the table, but it could also be that another framework also includes SQLite and they don't compile with `SQLITE_ENABLE_COLUMN_METADATA`, which could throw the results out a bit.

You could also try just embedding the framework, compiled here under releases, directly into your project.

Many thanks,
Adrian

**Comment by editfmah** [comment]
Hi, this has been fixed in v2.3.66 available under the releases tab.

**Comment by usman-whizpool** [comment]
how can i get 2.3.66.

**Comment by usman-whizpool** [comment]
i tried with this: SharkORM (~> 2.3.66).
which failed while pod install

**Comment by usman-whizpool** [comment]
this works: pod 'SharkORM', :git => 'https://github.com/sharksync/sharkorm.git', :branch => 'v2.3.66'

i hope its a right way to get it
