### ISSUE TITLE
Last version

### ISSUE THREAD

**Issue by Vanilil** [editfmah/sharkorm#15]
Is there any change to do in the last version, in order to make it work ? Cause since the 2.0.4, none of my requests works anymore.

**Comment by sharkorm** [comment]
We are just investigating now, it looks like something we fixed in production, that was pushed to Github, but was not included in the merge.  All of our tests pass on our local repo, but fail when we download the code from 2.0.4.  Yet we are showing no changes to push up/down.  We will get this fixed ASAP, as this is very embarrassing.

**Comment by editfmah** [comment]
2.0.5 has now been pushed and that issue should be fixed.  We are very sorry, as this should never have happened.  We have now changed our testing procedures to automatically test against the latest tag and not against our local repo.

**Comment by Vanilil** [comment]
Thanks for the quick fix.
