### ISSUE TITLE
How to set NULL for a column of 'double' type?

### ISSUE THREAD

**Issue by Parkyprg** [editfmah/sharkorm#21]
Hi,

I have a column which is of type "double". 
How can I set null for a specific record, instead of setting the value to 0?

If the object is created and this column was not set, then I have the null value. However, once I set a value for the first time, I cannot set it back to being empty.

Is there any chance to achieve this?

**Comment by editfmah** [comment]
Hi,

Unfortunately not, the only way to achieve this is to use an NSNumber type and not a double.  This is because the double type is not nullable, therefore Shark has absolutely no way to work out if there is no value set or it is 0 (or nil) in the class, the compromise being that if you use the non scalar type (NSNumber) to represent this, then it is nullable, because there is either a number or no number.

Thanks
Adrian

**Comment by Parkyprg** [comment]
Thank you Adrian for your fast response. NSNumber seemed to be the only solution for me too.

**Comment by editfmah** [comment]
Just to be clear, we're not being douchebags.  The problem comes from being unable to test the double,int,float value in a class as they are always defaulted to 0, and setting it to nil will also just set it to 0.  It's a really hard problem to solve.

That said, as soon as you set that double value, we turn it into an NSNumber anyway, so from a performance point of view, there will be absolutely no difference, because your call to [NSNumber doubleValue]  will have been made by the ORM anyway.
