### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by NurLight19** [editfmah/sharkorm#27]
How to perform database migrations? Lightweight or heavy migrations?

**Comment by editfmah** [comment]
Hi,

The addition, removal and changing of types within a class automatically triggers the refactoring of the database, as they are known progressions.

Removal of Class/Tables has to be done manually via a sql statement.

If new columns are added, and you specify a default value for that column, then that is put in upon creation (if memory serves, but I might be wrong about that, we can always sort that out fairly quickly).

There are some methods entityAtRevision:  and setRevision:  that are designed to give you the notification to recognise a schema change and make relevant changes to the objects, but we are not pushing that as a feature at the moment because we are investigating better ways to deal with column renames, or removal and what happens to the data.  Because at the moment it is very manual.  If you have examples of other systems that work very well then we would be happy to discuss, or you could add them yourself.  We will happily provide you with information about the revision process.

For possibly more info:
http://stackoverflow.com/questions/29629471/ios-dbaccess-migration-to-new-table-structure

Thanks
Adrian

**Comment by NurLight19** [comment]
Hi, Adrian.
Thank you for your quick and detailed answer!

**Comment by editfmah** [comment]
No thank you, we will add that to the list of things to document better (or at all)!

**Comment by lorenzoPrimi** [comment]
Hi @editfmah, just removing and (unused) column from the SRKObject model causes the db to corrupt.
How should the migration (delete a column) be handled?

**Comment by editfmah** [comment]
It should be automatic, we've not seen any corruption ourselves.  Do you get "database image malformed" ?

**Comment by lorenzoPrimi** [comment]
This is my schema: measurement_id is a field never used and always 0
<img width="400" alt="Screenshot 2019-03-29 at 20 02 13" src="https://user-images.githubusercontent.com/1616097/55249763-e80b4680-525d-11e9-8d33-723c15de48c1.png">

Once I remove `measurement_id` from the SRKObject model
I get DB error: no such column: etc...
And this is the new schema
<img width="400" alt="Screenshot 2019-03-29 at 20 04 26" src="https://user-images.githubusercontent.com/1616097/55249800-f6f1f900-525d-11e9-9d1a-cbb018843ddf.png">

**Comment by editfmah** [comment]
Ah right, are you using the CocoaPods version?

**Comment by lorenzoPrimi** [comment]
Using SharkORM (2.3.62)

**Comment by editfmah** [comment]
Because that repo is jammed up and I can't post the fixed version.  It is available to embed under releases [here](https://github.com/sharksync/sharkorm/releases/tag/v2.3.67).

**Comment by lorenzoPrimi** [comment]
I see, so installing that release would work?
Is there a way to install from Podfile via github or should I copy it manually in the project?

**Comment by editfmah** [comment]
Copy it manually, and i'll get onto the Pod guys again see if they can un-bugger the repo for me.

**Comment by editfmah** [comment]
But yes, that bug is definitely fixed.

**Comment by lorenzoPrimi** [comment]
Thanks for the help, I will use that version and switch to Pods once it will be fixed there too.
