### ISSUE TITLE
[Feature request] Support for raw SQL query.

### ISSUE THREAD

**Issue by mykolaj** [editfmah/sharkorm#42]
Hello!
Very handy ORM you've made.
If i may i'd like to request a feature.

Like the title says, it would be great to be able to execute a raw queries, so we could execute queries like:

```
SELECT city, MIN(salary) AS "lowest_salary"
FROM employees
WHERE state = 'AZ'
```

And to apply other SQL functions like: `AVG(), COUNT(), MAX(), MIN(), SUM()` 

NSDictionary could be a return value in Objective-C, and with Swift it could be something like list of tuples.

Thank you.

**Comment by editfmah** [comment]
Hi @mykolaj,

This was a frequent request, so it was included a couple of versions ago.  The interface is on the SharkORM class, and you get an SRKRawResult object back.

The SRKRawResult, contains an array of dictionaries.  But does have a couple of convenience methods to make it easier.

There is also count, sum, distinct, group methods as completion methods on the query objects.  But we have not implemented AVG, MAX or MIN.  We will add that to an upcoming version as it;s very easy to add those functions.

We always ask what people were trying to achieve with a raw query when using our ORM, if only to see if we are missing some functionality or whether we have not documented something thoroughly enough.

Raw queries are obviously useful in that you can succinctly  ask for exactly what you want, but have the downside of only retrieving data and not usable ORM objects.

So if you wouldn't mind us asking, what did you have planned for the raw query?

Thanks

**Comment by Parkyprg** [comment]
As you might already know, I have the other issue with performance on a simple query.
Let me tell you why I would like to be able to run a simple SQLite query, by giving you my own scenario, which I ran into:

I have a view which should show all the contacts from a table. Currently, there are 3000 rows in the table and it takes 2-3 seconds to get the results using `SRKQuery fetch`. This probably has to do that it takes each result and initiate a SRKObject on each and everyone. 
A. First try was with `fetch` method. This takes a long time to complete;

B. I tried to use `SRKQuery fetchLightweight`, but the time spent is not not good either. If I am not mistaken, it gets even worse, because I noticed (didn't spent too much time on it to investigate) - that the SRKQuery first brings all the ids and then it queries the database for each id and for each column individually. So for one single row it will make how many columns I have in the table many more queries. If I have 3 columns (name, phone, dateAdded), it will end up making 4 queries for the same row: 
1. select Id from contact;
2. select name from contact limit 1;
3. select phone from contact limit 1;
4. select dateAdded from contact limit 1

So I don't think I truly understand how I can use fetchLightweight method.

C. I tried also to use `SRKQuery ids`. This one is pretty fast but I have the following situation: I need to show on SectionIndex view all the letters found in the table. Without getting the list of all the names, I cannot do this properly using ids.

I ended by running 2 queries - one which fetch first 50 rows and displays them and then on a background thread the full query. This the problem in point C exists.

So I would like a method like rawQuery to give it a plain simple query and retrieve back sqlite3_column results and I will properly handle each column based on a known type, since I am supplying the rawQuery.

**Comment by mykolaj** [comment]
Here's one more case.

I have records in a table which has a timestamp field. Lets call their corresponding ORM
object a 'Meal'. Now i'd like to know unique dates when at least one Meal exists.

```
SELECT timestamp
FROM meals
GROUP BY strftime('%Y-%m-%d', (datetime(timestamp / 1000, 'unixepoch')));
```

You can see that there's a SQLite function datetime() is applied. There's no way to do it
that easy as this using only fetch() method. Not to mention it would be super inefficient to select all 
records and perform search on a result.

**Comment by editfmah** [comment]
@mykolaj, this is true. And I guess that's why we put the rawQuery method in.  GroupBy & partial selects are tricky, lightweightObjects go some way towards that by allowing you to specify the columns you do wish to retrieve, but they do still make a class for a row which is both costly and slower than any kind of raw query would ever be, an obviously don't work with group selects.

Although that can be achieved using the distinct method too, which is also going to form part of my answer to @Parkyprg in a moment.

So if you have any suggestions that could be implemented as extensions to the query class, but that would also be generic enough to provide additional functionality then i'd be happy to take that onboard.

**Comment by editfmah** [comment]
@Parkyprg , so we do have a raw query method on the SharkORM class as detailed above, and of course you can use it.  But just a couple of points that may be useful:

1)  if you use:

`- (SRKResultSet*)fetchLightweightPrefetchingProperties:(NSArray*)properties;`

This allows you to fetch in one go, only the columns that are needed, which is faster and more efficient.  But it probably still won't be fast enough on a device where you need to query 3k objects.  So that brings me to the next alternative:

2) You can use the distinct method to get the first character of all of those entries, which will be very fast.  And then use a fetch, but specify a batch size.  Then it will only load into the array the amount of data you need to show on the screen at the time.  This is also not entirely perfect, and depending on the size of the batch, you may wish to optimise how the tableview asks for the extra data to make it smooth.

3)  Use the draw query method:

`+(SRKRawResults*)rawQuery:(NSString*)sql;`

Thanks
Adrian

**Comment by editfmah** [comment]
@Parkyprg & @mykolaj can I close this particular query off as we already have this feature?

**Comment by mykolaj** [comment]
@editfmah

I figured that `SharkORM.rawQuery(sql: String!)` is the method i was looking for. So i'm good with that.

Thank you
