### ISSUE TITLE
Schema is not updating after adding a new Entity

### ISSUE THREAD

**Issue by PabloHazan** [editfmah/sharkorm#52]
Hi!

I'm trying to use SharkORM to make a simple data model, based on the example (Swift). So I've declared a new entity on my project that inherits from `SRKObject`.  

```swift
import Foundation
import SharkORM

class Meal : SRKObject {
  dynamic var name: String?
  dynamic var rating : NSNumber?
}
```

After launching the app with the new changes, I've inspected my `database.db` file and the original schema doesn't update. 

The only way that I've found to update the schema is by creating a new object of my new Class or just calling a class method (like `query`)

Is this the expected behavior? How should I initialize a full schema based on all the entities that inherit from `SRKObject`?

**Comment by editfmah** [comment]
Hi @PabloHazan,

This is expected behaviour, in that objects refactor themselves on the first call.  The whole mantra of Shark/DBAccess was to be super low impact for developers and to try and do everything possible to reduce coding effort, or things you have to know about.

Because the common upgrade paths are adding a new property or maybe changing a property type, it is feasible to refactor these tables on the fly as SQLite does not re-write the data and can complete these changes almost instantly.

The only known issue is that you may reference a field that does not exist (yet) from a free text query, and that will obviously error.  But any use of embedding of the other class to form a subquery or a join will trigger the refactor event before the query is run, so it is a very unusual circumstance that can lead to any problems.

That said, you can always just make a call to the +setupTablesFromClasses: and pass in a list of classes.  The function does nothing, accept ensure the tables are all refactored ahead of other code running.

This can also be achieved by just creating an array of the class's too.
