### ISSUE TITLE
[Feature Request] Integrate raw sql query into transaction....

### ISSUE THREAD

**Issue by lbwxly** [editfmah/sharkorm#55]
I think there are two features can be added into the library.
1. integrate raw sql query into transaction if it is called in a transaction.
2. provide another transaction api, caller can cancel the transaction by return a false value. it can be implemented by add another api to accept the new transaction block definition:
typedef bool(^SRKCancellableTransactionBlockBlock)();

just some thought, i can make some changes and create the pull request if you accept this feature.

**Comment by editfmah** [comment]
Hi @lbwxly,

Sorry i've been swamped of late and with a 1-Month vacation progress has been rather slow,  but in principal, if there is no obvious way to re-utilise the existing call structure and remain compatible, we could add a different type and call.

I'm not so sure about including SELECT's arbitrarily in the transaction, over just throwing errors which cancel the transaction on every iteration over an object.

But there would also need to be some rollback functionality added to SRKObject, e.g. some kind of to and from Dictionary function for use by the transaction to restore everything back.  Because I was looking into a weakness in the transaction model, in which the data layer is entirely correct but the values of properties can be left in an incorrect state (e.g. if set on an entityWillUpdate etc..).

There is a branch for new faster transactions, which can be deleted now as it may be faster but it also showed me the failures of the current model.

Also, it might be worth looking into naming transactions so a transaction can spread across multiple threads if necessary.  But if I remember rightly the rollback had some very weird caveats if multiple simultaneous transactions were in play.

Just to let you know, i've got some branches for the following which I am splitting out from your last pull request:

![screen shot 2016-12-13 at 13 28 58](https://cloud.githubusercontent.com/assets/3480030/21142036/29239be0-c138-11e6-9b75-9f6160eba246.png)

But obviously i'll do the other things first and i'll not touch transactions if you are taking a look at that specifically.

The thing I have changed that will be affecting transactions is that there is some duplicate code to build the statements and trigger events which can all be brought into a single class.  So a merge might be interesting.  Don't know if you might want to just wait for that to get checked in before making a start?  I can work on it and get it finished today if you are waiting to look at this.

Thanks
Adrian

**Comment by lbwxly** [comment]
@editfmah sorry for the late reply,i won't start immediately, i may start working on that when i have time in the late of this month. at that time, we can have a chat on this to see if your change has already cover this.

**Comment by editfmah** [comment]
@lbwxly Cool, i'll press on with some re-factoring here, as actually the whole transaction model as it is is fundamentally flawed (i have no ideas what drugs i was on at the time).  So,  there should also be some big improvements in performance to be had too.

**Comment by editfmah** [comment]
@lbwxly okay, the re-write of the transaction handler is complete:

_Here is an outline of what has been changed:_

**Features/Improvements:**

- Transactions are now fully isolated by thread. 

- Transactions are failed if ANY error occurs, including a syntax error in a query.

- Any modifications to an object, it’s relationships or any changes it makes using triggers or the trigger methods (entityWillUpdate, delete etc) for cascading actions will also be rolled back, not just the SQL table contents but the entire object stack will be as it was before you called the transaction. 

- You can manually fail a transaction using ‘SRKFailTransaction()’, for any application logic you wish to apply.

It has been thoroughly tested and seems to work great, it's certainly a lot faster for heavy delete operations than before.

So I think this deals fairly comprehensively with your second point, but i'm still not quite sure what  you mean by 'raw sql' in your first point?

**Comment by lbwxly** [comment]
@editfmah 
My first point is if i call raw sql query in a transaction, the result of the raw sql query should also be managed by the transaction.
e.g. SRKTransaction.transaction:{
    SharkORM.rawQuery("Delete from User where id = 1")
} rollback:{
}

the query "Delete from User where id = 1" shouldn't be executed immediately, it should be commit in the transaction's commit.

**Comment by editfmah** [comment]
@lbwxly ok awesome, thanks for getting back to me.  That has also been changed and pushed in now.  I am just preparing the pod release, and documentation.
