### ISSUE TITLE
Database model migration mechanism?

### ISSUE THREAD

**Issue by Narayane** [editfmah/sharkorm#63]
Hi,

don't see any content on database model migration mechanism in README.

Does anything exist?

Thanks.

**Comment by editfmah** [comment]
Hi @Narayane,

It does indeed, it's mostly automatic.  We do have a revision based system as well, but it should be avoided in the very near term as we are likely to revise exactly how it works.

TL;DR; version:
All tables are automatically refactored to match your classes.

But the basics are here:
https://github.com/sharksync/sharkorm/issues/27

It seems I was supposed to document it last year as well, i'll have to stick a post-it to my screen to make sure I remember.

**Comment by mattvb91** [comment]
Just checking in about this too. As you mentioned in above referenced issue the entityAtRevision and setRevision would be a huge benefit on my own projects as its rare to not have some kind of object changes on bigger projects when migrating the schema.

+1 for official documentation in readme

**Comment by editfmah** [comment]
Hi @mattvb91 / @Narayane , to explain the issue as it exists right now.

entityAtRevision & setRevision works by calling a class method once on an object to tell you which revision your object model is at, and you get to then "replay" upgrade scripts to make any changes that are required.

The problem comes from several directions here:

The **entityAtRevision**: call happens when the object model has been inspected and all "new" columns have been added, but the removed columns have not yet been removed.  This gives you the opportunity to copy data from one column to another in the case of a rename, or pre-populate a column with data if it is indeed a new column.

But at the moment, you have to use the **executeSQL** interface to perform any of these actions.  And the reason we have not gone beyond this simplistic implementation is that we feel that we should probably be doing something using the object model itself, e.g. you supply a block which receives an object, plus a dictionary of the columns which are being dropped, and then we can execute that on a row-by-row basis across many threads.  The downside is that it will be quite slow and at that point the class will contain only your new model, and you would only be able to reference the current properties.

There is also a problem with someone jumping versions, as there is no "replay" in the schema change, it is just refactored there and then to the new shape.  So, the jump from a->b->c missing b may error, because the script for "b" would maybe reference a column which has now been removed in "c" and was only created in "b".

So, as the main use case is the renaming or removing of columns only we had been thinking about having events like **entityColumnAdded:** and **entityColumnRemoved**: with some detail about what was happening, maybe giving the opportunity to supply some new values, or take the old values, but this would also be very clunky as code you had written which referenced defunct properties would then break compilation.

Our preferred route would be to have a GUI to design the data models and track all the changes, therefore being able to create migration scripts easily. or tightly integrate a language such as lua within SQLite with functions accepting JIT script that would enable simple transformation and assignment to objects such as:

```
column1 = column2 -- for deleted column2
if column3 ~= nil then
     column3 = 123.45
end
```

Which would be flexible and fast, but is yet another language to understand or technology to learn.  That said, we could use Swift/Obj-c code to generate it, but allow developers to manually specify code to run if the simplistic interface is not going to be enough.

So, we arrive here, with no perfect solution to the problem but with the founding mantra of Shark/DBAccess.  Which is:

The developer should have to do nothing if possible and should never be caught out (like a model change crash in CoreData), as much as reasonable possible should be entirely automatic.

So I invite feedback, how would others solve this issue?

**Comment by editfmah** [comment]
No feedback, but a block added to documentation.
