### ISSUE TITLE
Fetching objects from DB doesn`t work  Swift 3

### ISSUE THREAD

**Issue by JULI-ya** [editfmah/sharkorm#68]
.fetch() function returns me requested objects with all nil fields or empty values. I have tried the simple code example and I have got the same behaviour.  Using Swift 3, xCode 8.2.1

```
       var newEmployee = Employee()
        newEmployee.name = "Steve"
        newEmployee.age = 54
        newEmployee.commit()
        
        let result = Employee.query().fetch()
        
        var employeeCount = result?.count
        
        for var employee in result! {
            let empl = employee as! Employee
        }
        
        let youngest = Employee.query()
            .where(withFormat: "age < %@", withParameters: [50])
            .order(by: "age")
            .limit(10)
            .fetch()
        
        employeeCount = youngest?.count
    }
```
    
`class Employee: SRKObject {
    var name: String?
    var age: Int?
}`

And what I see:

<img width="866" alt="screen shot 2017-03-22 at 2 45 14 pm" src="https://cloud.githubusercontent.com/assets/1420102/24217566/4f03db62-0f0e-11e7-8fcc-50f17b5ea4c8.png">

**Comment by editfmah** [comment]
Hi @JULI-ya 

class Employee: SRKObject { var name: String? var age: Int? }

Should be:

class Employee: SRKObject {dynamic var name: String? dynamic var age: Int32! }

Because "Int" is not supported in Objective-c, and does not support dynamic dispatch.

**Comment by JULI-ya** [comment]
@editfmah doesn`t help!
I tried all variants before, but did it again after your comment =)
<img width="634" alt="screen shot 2017-03-22 at 4 01 39 pm" src="https://cloud.githubusercontent.com/assets/1420102/24220653/1da3e642-0f19-11e7-9faf-7d469a9eb06d.png">
<img width="1139" alt="screen shot 2017-03-22 at 4 04 09 pm" src="https://cloud.githubusercontent.com/assets/1420102/24220681/3c2ffb28-0f19-11e7-8875-086b1af262d6.png">

**Comment by editfmah** [comment]
Sorry about the Int32 type, that will obviously need to be NSNumber not Int32.
Okay, is it showing nil when you PO the object?  Because nil, when you hover over it is an outstanding bug with LLDB when a swift object is subclassed from an NSObject where the properties are dynamic and the get/set methods have been swizzled.  We are looking into how to fix this at this precise moment.

https://github.com/sharksync/sharkorm/issues/24

**Comment by JULI-ya** [comment]
Sorry, what does mean PO the object? Fields are actually nil, not only in the debugger window. I have no idea, how to fix it

**Comment by editfmah** [comment]
so if you look in the database, does the schema get created?  are the records there but the columns all have NULL in them?  or do they have the values you would expect?

**Comment by JULI-ya** [comment]
@editfmah ok, you were right! I`ve changed age type to the NSNumber and checked actual values. They are not nil now, but debugger still shows me nil. It is confusing, especially for new ios developers like me =)

PS Maybe obvious question, but any way... where is database file stored in the device filesystem and how can I access to it to take a look what`s inside?)

**Comment by Parkyprg** [comment]
@JULI-ya - if you are running the app on a simulator, check under:
~/Library/Developer/CoreSimulator/Devices/{deviceID}/data/Containers/Data/Application/{ApplicationID}/Documents/

You should find {dbName}.db which can be opened with any SQLite editor.

**Comment by JULI-ya** [comment]
Ok, guys, thank you for help! I moved forward and got one more question:

How to use  `CommitOptions.ignoreEntities ` property? 

I have an array of objects as a field ( like `dynamic var camerasList: [Camera]?`) and I want to ignore it by Shark ORM.

**Comment by editfmah** [comment]
This has been answered on SO.

**Comment by mattvb91** [comment]
@editfmah didn't want to open a new issue for this so just checking in here as seems relevant to what others may search & didnt find anything in changelog.

Has .object(withPrimaryKeyValue: id) been replaced by .init(primaryKeyValue: id) for Swift3 correct? Just double checking im not mistaking this for other functionality.

**Comment by editfmah** [comment]
Hi @mattvb91,

We changed the Obj-c definition from:
`- (id)initWithPrimaryKeyValue:(NSObject*)priKeyValue;`

to:
`- (instancetype)initWithPrimaryKeyValue:(NSObject*)priKeyValue;`

And this seems to have changed the way swift names it's mapped methods.  It was not deliberate, and slightly strange behaviour.  I have absolutely no idea where the "object" ever came from, it feels like a bug to me (in XCode).

**Comment by mattvb91** [comment]
Huh well I am using the correct syntax now thank you. As I cant find .object anywhere in the documentation it must have just popped up in the autocomplete in xcode & somehow worked.

**Comment by editfmah** [comment]
Yeah, Apple automatically generates it, for some odd reason.  I might ask them in June if I get a chance.

**Comment by editfmah** [comment]
Ah no, now I see:

There are two definitions one initWithPrimaryKey() and the other is objectWithPrimaryKey:.

Now it looks like the init() call never mapper properly with Swift because the return type was not instancetype, and Swift didn't understand that it was an initialiser. 

Now the difference is that myClass(withPrimaryKeyValue:) will create a new object and pre-populate the PK value.

But objectWithPrimaryKey, is different in that it queries for an object in the database and if not found will return nil.  It is purely a convenience method to help with getting known object back out again.

**Comment by mattvb91** [comment]
So just to confirm with your above expected behaviour  & for future reference too. I am now using:

    let object = Object.init(primaryKeyValue: id)

To LOAD an existing object from the DB. If I do a debugPrint(object) it successfully prints all of my expected values retrieved from the DB. I dont have any .object methods available to me anymore (which to my understanding is now expected). I'm on Swift 3.1 by the way.

I am experiencing some issue with other models when I perform a isEqual(_ object: Any?) -> Bool on the loaded object but I think that is an issue with my code not SharkORM. Let me know if you want me to open a new issue. Dont want to derail this thing completely. Thanks
